# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: /test-runner
    groups:
      test-runner:
        patterns:
          - "*"
    package-ecosystem: pip
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - directory: /pytorch
    groups:
      pytorch:
        patterns:
          - "*"
    package-ecosystem: pip
    schedule:
      interval: weekly
  - directory: /classical-ml
    groups:
      classical-ml:
        patterns:
          - "*"
    package-ecosystem: pip
    schedule:
      interval: weekly
  - directory: /tensorflow
    groups:
      tensorflow:
        patterns:
          - "*"
    package-ecosystem: pip
    schedule:
      interval: weekly
  - directory: /python
    groups:
      python:
        patterns:
          - "*"
    package-ecosystem: pip
    schedule:
      interval: weekly
  - directory: /docs
    groups:
      docs:
        patterns:
          - "*"
    package-ecosystem: pip
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /classical-ml
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/classical-ml
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/data-analytics
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/deep-learning
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/inference-optimization
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /python
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /pytorch
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /pytorch/serving/model-store
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tensorflow
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tensorflow/serving
    schedule:
      interval: daily
