# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "test-runner/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: ".github/workflows" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /classical-ml
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/classical-ml
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/data-analytics
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/deep-learning
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /preset/inference-optimization
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /python
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /pytorch
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /pytorch/serving/model-store
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /pytorch/serving
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tensorflow
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tensorflow/serving
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /test-runner
    schedule:
      interval: daily
