---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
    - name: rest
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30111
      {{- else }}
      targetPort: 30111
      {{- end }}
      port: 8501
    - name: grpc
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30110
      {{- else }}
      targetPort: 30110
      {{- end }}
      port: 8500
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
