# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- Name of the serving service
nameOverride: ""
# -- Full qualified Domain Name
fullnameOverride: ""
deploy:
  # -- Intel Optimized torchserve image
  image: intel/intel-optimized-pytorch:2.3.0-serving-cpu
  # -- Add Environment mapping
  env:
    configMapName: intel-proxy-config
    enabled: true
  # -- Set token authentication on or off. Checkout the latest [torchserve docs](https://github.com/pytorch/serve/blob/master/docs/token_authorization_api.md) for more details.
  tokens_disabled: true
  # -- Models to be loaded
  models: all
  # -- Model Server Configuration file location
  modelConfig: /home/model-server/config.properties
  # -- Number of pods
  replicas: 1
  resources:
    # -- Maximum resources per pod
    limits:
      cpu: 4000m
      memory: 1Gi
    # -- Minimum resources per pod
    requests:
      cpu: 1000m
      memory: 512Mi
  storage:
    # -- Network File System (NFS) storage for models
    nfs:
      enabled: false
      server: nil
      path: nil
      readOnly: true
      subPath: nil
service:
  # -- Type of service
  type: NodePort
pvc:
  # -- Size of the storage
  size: 1Gi
