# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Integration Test
description: 'https://github.com/intel/ai-containers/blob/main/test-runner/README.md'
author: tyler.titsworth@intel.com
inputs:
  cache_registry:
    description: 'Container Cache Registry URL'
    required: false
    type: string
  perf_repo:
    description: 'Performance Test Repo'
    required: false
    type: string
  recipe_dir:
    description: 'Path to Recipe Directory'
    required: true
    type: string
  registry:
    description: 'Container Registry URL'
    required: false
    type: string
  repo:
    description: 'Container Repository'
    required: true
    type: string
  test_dir:
    description: 'Path to Test Dir'
    required: true
    type: string
  token:
    required: true
    type: string
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        path: mlops
        ref: main
        repository: intel/ai-containers
        token: ${{ inputs.token }}
    - uses: actions/checkout@v4
      with:
        path: models-perf
        ref: main
        repository: ${{ inputs.perf_repo }}
        token: ${{ inputs.token }}
    - name: Install Requirements
      shell: bash
      run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r mlops/test-runner/requirements.txt
    - name: Test
      shell: bash
      run: venv/bin/python mlops/test-runner/test_runner.py -f ${{ inputs.test_dir }}/tests.yaml -l ${{ inputs.test_dir }}/logs -a ${{ inputs.recipe_dir }}/.actions.json -v
      env:
        CACHE_REGISTRY: ${{ inputs.cache_registry }}
        PYTHONPATH: mlops/test-runner
        REGISTRY: ${{ inputs.registry }}
        REPO: ${{ inputs.repo }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
    - name: Print Log Summary
      shell: bash
      if: always()
      run: echo -e "\`\`\`\n$(cat ${{ inputs.test_dir }}/logs/test-runner.log)\n\`\`\`" >> $GITHUB_STEP_SUMMARY
    - name: Get Test Name
      shell: bash
      if: always()
      run: echo "test=${{ inputs.recipe_dir }}-$(basename ${{ inputs.test_dir }})" | tr '/' '_' >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.test }} outputs
        path: ${{ inputs.test_dir }}/logs
        overwrite: true
