# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  idp:
    build:
      args:
        IDP_VERSION: ${IDP_VERSION:-core}
      labels:
        dependency.conda.intel-distribution-for-python: intelpython3_${IDP_VERSION:-core}
        docs: python
        org.opencontainers.image.name: "intel/python"
        org.opencontainers.image.title: "Intel® Distribution for Python Base Image"
        org.opencontainers.image.version: 3.10-${IDP_VERSION:-core}
    image: ${REGISTRY}/${REPO}:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-idp-${IDP_VERSION:-core}-py${PYTHON_VERSION:-3.10}-base
