name: Docker Info Page Publish
on:
  push:
    branches: [ "main" ]
#env:
#  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - uses: actions/checkout@v4
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(jq -c . < .github/workflows/dockerhub-readmes.json)" >> $GITHUB_OUTPUT
#  print:
#    runs-on: ubuntu-latest
#    needs: setup-matrix
#    strategy:
#      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
#    steps:
#     - run: echo "${{ matrix.readmes.fname }} -> ${{ matrix.readmes.repo-name }}"
  PublishDockerHubDescription:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ matrix.readmes.repo-name }}
          readme-filepath: ${{ matrix.readmes.fname }}
