name: Docker Info Page Publish
on:
  push:
    branches: [ "main" ]
#env:
#  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - uses: actions/checkout@v4
     - name: Set matrix data
       id: set-matrix
       run: |
         pwd
         echo "matrix=$(jq -c . < .github/workflows/dockerhub-readmes.json)" >> $GITHUB_OUTPUT
  print:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
     - run: echo "${{ matrix.fname }}} -> ${{ matrix.repo-name }}}"
  PublishDockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jitendraintel/test1
          readme-filepath: ./docs/dockerhub/test1.md
